# Generated by Django 5.2 on 2025-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_comment_comment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
