# Generated by Django 5.2 on 2025-04-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_alter_task_expected_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='actual_end_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expected_end_date',
        ),
    ]
