# Generated by Django 5.2 on 2025-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_rename_actual_end_date_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='in progress', max_length=20),
        ),
    ]
